{
  "value": "function\")thrownewTypeError(\"Callbackmustbecallable.\")",
  "correct": true,
  "jSonReason": "re_ast1"
}